#!/bin/bash

for v in {1..10}
 do
  echo "$v$(($v+1))$(($v+2))" > lab2_file_"$v"
done

files=`ls`
for f in $files
 do 
  if [ "${f:0:10}" = "lab2_file_" ]
  then
    echo $f:
    cat $f
  fi
done

for z in $files
 do
  if [ "${z:0:10}" = "lab2_file_" ]
  then
   rm $z
  fi
done
